### ISSUE TITLE
GNOME: Incorrect sizes and multi monitor support behavior

### ISSUE THREAD

**Issue by lutzseverino** [leukipp/cortile#37] opened 2024-01-11 10:46 UTC
## Problems
- On the primary screen, windows are not properly sized due to the top bar being present. Cortile is not considering this, hence windows are being pushed out the bottom.
- Automatic window placement looks jagged, probably due to the multiple monitors present on my setup.
- Windows are never automatically placed on my primary monitor and moving them around monitors is incredibly annoying and unstable.
- Systray never starts and is not present.

## Thoughts
Accounting for the GNOME top bar is probably possible through the config, but I'm reporting it since it could be caused by a bigger issue. 

Proper multimonitor support could probably be achieved, but a quick workaround (that would add as a nice feature) would be to disable cortile completely on monitors of your choice.

For example, I myself wouldn't want to tile windows on my secondary monitor, floating there is alright.

### Video

https://github.com/leukipp/cortile/assets/28309837/a755a6d9-4e17-4e5a-9b59-ed61ded98f2f

**Comment by leukipp** [comment] 2024-01-11 14:23
> Accounting for the GNOME top bar is probably possible through the config, but I'm reporting it since it could be caused by a bigger issue.

I assume you are using GNOME with mutter, where panel auto detection doesn't work (https://github.com/leukipp/cortile/issues/27#issuecomment-1849064547) and there is no know fix for this ATM. You can use the  `edge_margin`  and `edge_margin_primary`  config entries to account for additional margins.

> Proper multimonitor support could probably be achieved, but a quick workaround (that would add as a nice feature) would be to disable cortile completely on monitors of your choice.

Actually cortile disables/enables tiling per monitor, depending on your mouse position when execution the keyboard shortcut as discussed here (https://github.com/leukipp/cortile/issues/16#issuecomment-1614853032). If this is not the case under GNOME let me know, as this could be related to some other issues.

> Windows are never automatically placed on my primary monitor and moving them around monitors is incredibly annoying and unstable.

Some distros and/or individual applications may reload the latest window position, which could cause issues for cortile. Please try to find your default behavior when cortile is not executed and then compare it when running `cortile -v -cache 0`. This disables the internal cortile cache, which would also try to reload the latest window positions.

> Systray never starts and is not present.

For the systray issue you should have a look into the [systray](https://github.com/fyne-io/systray) library (which is used by cortile). For GNOME `snixembed` and `gnome-shell-extension-appindicator` is mentioned there.

Please also check the [issues](https://github.com/leukipp/cortile#issues-) section, cortile is known to have some problems in GNOME (mainly caused by poor EWMH implementations).

**Comment by leukipp** [comment] 2024-01-16 15:15
Please try the latest [v2.3.2](https://github.com/leukipp/cortile/releases/tag/v2.3.2) release and let me know if some of the mentioned issues have been improved.

**Comment by lutzseverino** [comment] 2024-01-17 13:44
Sorry, I haven't had any time to test this, (or to address your first message) but I'll get back to you between today and tomorrow.

**Closed** 2024-11-02 18:45 UTC
Labels: enhancement
